### ISSUE TITLE
Import konva/lib/core

### ISSUE THREAD

**Issue by giovanni-bertoncelli** [ctinnovation/ngx-konva#28]
**Describe the bug**
Upgrading to latest version of Konva  (9.3.6) I get this error:
```
ERROR TypeError: Cannot read properties of undefined (reading 'isDragging')
    at Object.isDragging (Global.js:46:36)
    at Stage._pointerleave (Stage.js:349:46)
    at content.addEventListener.passive (Stage.js:308:33)
    at _ZoneDelegate.invokeTask (zone.umd.js:445:35)
    at core.mjs:10757:55
    at AsyncStackTaggingZoneSpec.onInvokeTask (core.mjs:10757:36)
    at _ZoneDelegate.invokeTask (zone.umd.js:444:64)
    at Object.onInvokeTask (core.mjs:11070:33)
    at _ZoneDelegate.invokeTask (zone.umd.js:444:64)
    at Zone.runTask (zone.umd.js:210:51)
```
**Expected behavior**
Any mouseout event listener should not trigger that error.

**Solution**
As proposed here: https://github.com/konvajs/konva/issues/1730#issuecomment-1999326338, ngx-konva should import `konva/lib/core` inside the application.
See also: https://github.com/konvajs/konva?tab=readme-ov-file#3-minimal-bundle

Relates also to: #26

**Comment by giovanni-bertoncelli** [comment]
Fixed in `16.1.6`
